version: '3'
services:
  eth1:
    image: ethereum/client-go:stable
    command: --goerli --syncmode light --datadir /ethdata --http --http.addr '0.0.0.0' --http.api eth,web3,debug,txpool,net,h,db,admin,debug --ws --ws.api eth,web3,debug,txpool,net,h,db,admin,debug  --ws.addr '0.0.0.0' --gcmode full
    container_name: eth1
    volumes:
      - datadir:/ethdata
    ports:
    - "8545:8545"
    - "8546:8546"
    - "8547:8547"
    - "30303:30303"
networks:
  default:
    external:
      name: eth-goerli-test
volumes:
  datadir:
